<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner.Oracle" Version="7.0.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj" />
  </ItemGroup>

</Project>
