<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner.Oracle" Version="8.0.1" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj" />
  </ItemGroup>

</Project>
