//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseWebLibrary.WebSite.TestPages {
    
    
    public partial class ChecklistDemo {
        
        /// <summary>
        /// checkList3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.Checklist checkList3;
        
        /// <summary>
        /// checklist control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.Checklist checklist;
        
        /// <summary>
        /// checklist2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.Checklist checklist2;
    }
}
