//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedStapler.TestWebSite.TestPages {
    
    
    public partial class FormFieldDemo {
        
        /// <summary>
        /// dropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfListControl dropDownList;
        
        /// <summary>
        /// toggler control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.ToggleButton toggler;
        
        /// <summary>
        /// dateRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow dateRow;
        
        /// <summary>
        /// datePicker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.DatePicker datePicker;
        
        /// <summary>
        /// textBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfTextBox textBox;
        
        /// <summary>
        /// timePicker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.TimePicker timePicker;
        
        /// <summary>
        /// choiceList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfListControl choiceList;
        
        /// <summary>
        /// parentList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfListControl parentList;
        
        /// <summary>
        /// dependentList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.DependentDropDownList dependentList;
        
        /// <summary>
        /// mailto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.MailtoLink mailto;
        
        /// <summary>
        /// image control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image image;
        
        /// <summary>
        /// image1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image image1;
        
        /// <summary>
        /// datepicker1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.DatePicker datepicker1;
        
        /// <summary>
        /// datepicker1value control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal datepicker1value;
        
        /// <summary>
        /// mirroredDatepicker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.DatePicker mirroredDatepicker;
        
        /// <summary>
        /// mirroredDatepickerValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal mirroredDatepickerValue;
        
        /// <summary>
        /// freeFormRadioListTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder freeFormRadioListTest;
        
        /// <summary>
        /// buttonPlace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder buttonPlace;
        
        /// <summary>
        /// controlValues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.ControlStack controlValues;
        
        /// <summary>
        /// ph control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder ph;
    }
}
