//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseWebLibrary.WebSite.TestPages {
    
    
    public partial class ToolTipTest {
        
        /// <summary>
        /// ph control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder ph;
        
        /// <summary>
        /// label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfLabel label;
        
        /// <summary>
        /// extra control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel extra;
        
        /// <summary>
        /// calendarTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.MonthViewCalendar calendarTest;
        
        /// <summary>
        /// controlStack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.ControlStack controlStack;
        
        /// <summary>
        /// ewfCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfCheckBox ewfCheckBox;
        
        /// <summary>
        /// ewfLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfLabel ewfLabel;
        
        /// <summary>
        /// ewfListControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfListControl ewfListControl;
        
        /// <summary>
        /// ewfImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.EwfImage ewfImage;
        
        /// <summary>
        /// ewfCheckList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.Checklist ewfCheckList;
        
        /// <summary>
        /// ewfDatePicker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.DatePicker ewfDatePicker;
        
        /// <summary>
        /// ewfDateTimePicker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.DateTimePicker ewfDateTimePicker;
        
        /// <summary>
        /// mailtolink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.MailtoLink mailtolink;
        
        /// <summary>
        /// timepicker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RedStapler.StandardLibrary.EnterpriseWebFramework.Controls.TimePicker timepicker;
    }
}
