trigger:
  branches:
    include:
    - master
    - Integration
  paths:
    include:
    - '@@TriggerPath'

pool: EwlBuild

steps:
- task: UseDotNet@2
  inputs:
    version: '@@DotNetVersion'